# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 06:38
from __future__ import unicode_literals

import chatbot.apps.common.model_fields
from django.db import migrations
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170418_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertnotetemplate',
            name='body',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='expertnotetemplate',
            name='name',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='action',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='additional_income_amount',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='additional income amount'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='averageInterestRate',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='average interest rate'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='basic_hardship',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='basic hardship'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='behindOnPayments',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='behind on payments'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='conclusion',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, default='None', max_length=1000000000, null=True, verbose_name='conclusion'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='credit_score_importance',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='credit score importance'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='daysPastDue',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='days past due'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='employment_status',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='employment status'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='expert_note',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='expert note'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='expert_note_template_name',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, default='None', max_length=1000000000, null=True, verbose_name='expert note template name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='firstName',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='homeEquity',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='home equity'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='houseHoldSize',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='household size'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='incomeAmount',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='income amount'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='incomeConsistency',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='income consistency'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='incomeYN',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='income YN'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='intercom_user_id',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='intercom user id'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='knowWhereToStart',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='know where to start'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='monthlyDebtPayments',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='monthly debt payments'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='needs_future_auto_loan',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='needs future auto loan'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='needs_future_mortgage',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='needs future mortgage'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='needs_future_student_loan',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='needs future student loan'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ownHome',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='own home'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phoneOrEmail',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='phone or email'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='questionConsultation',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='question consultation'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='session_id',
            field=chatbot.apps.common.model_fields.LongCharField(default=uuid.uuid4, max_length=1000000000, unique=True, verbose_name='session id'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='situationDetail',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='situation detail'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='totalDebt',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='total debt'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_status',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, default='None', max_length=1000000000, null=True, verbose_name='conclusion'),
        ),
    ]
