# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20170418_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=2048, null=True, verbose_name='email address'),
        ),
    ]
