# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer_name', models.TextField(blank=True, null=True, verbose_name='employer name')),
                ('employment_length', models.TextField(blank=True, null=True, verbose_name='employment length')),
                ('income_consistency', models.TextField(blank=True, null=True, verbose_name='income consistency')),
                ('income', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='income')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
