# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True, verbose_name='name')),
                ('phone', models.TextField(blank=True, null=True, verbose_name='phone')),
                ('total_debt', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('settlement_target_pre', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='settlement target pre')),
                ('settlement_target_post', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='settlement target post')),
                ('risk_level', models.PositiveIntegerField(blank=True, null=True, verbose_name='risk level')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
