# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 06:38
from __future__ import unicode_literals

import kirkwood.apps.common.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employer_name',
            field=kirkwood.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='employer name'),
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_length',
            field=kirkwood.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='employment length'),
        ),
        migrations.AlterField(
            model_name='job',
            name='income_consistency',
            field=kirkwood.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='income consistency'),
        ),
    ]
