# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 10:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotionAI',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.TextField(blank=True, null=True, verbose_name='session id')),
                ('bot_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='bot id')),
                ('module_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='module id')),
                ('reply', models.TextField(blank=True, null=True, verbose_name='reply')),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='raw data')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
