# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debts', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='user_profile',
            field=models.ForeignKey(help_text='The user profile that this debt belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='profiles.UserProfile', verbose_name='user profile'),
        ),
    ]
