# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creditor_name', models.TextField(blank=True, null=True, verbose_name='creditor name')),
                ('collection_agency', models.TextField(blank=True, null=True, verbose_name='collection agency')),
                ('type', models.TextField(blank=True, null=True, verbose_name='type')),
                ('status', models.TextField(blank=True, null=True, verbose_name='status')),
                ('money_movement', models.TextField(blank=True, null=True, verbose_name='money movement')),
                ('last_paid_at', models.DateField(blank=True, null=True, verbose_name='last paid at')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='balance')),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='interest rate')),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='monthly payment')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
