# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 06:38
from __future__ import unicode_literals

import chatbot.apps.common.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0002_debt_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='collection_agency',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='collection agency'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='creditor_name',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='creditor name'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='money_movement',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='money movement'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='status',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='type',
            field=chatbot.apps.common.model_fields.LongCharField(blank=True, max_length=1000000000, null=True, verbose_name='type'),
        ),
    ]
